#!/usr/bin/env bash

set -e

[ -z "$ETH_DEVICE" ] && export ETH_DEVICE="$(ip route show default | awk '{ print $5 }')"
[ -z "$IP_ADDRESS_CIDR" ] && export IP_ADDRESS_CIDR="$(ip -o addr show "$ETH_DEVICE" | awk '{ print $4 }')"
export CIDR="${IP_ADDRESS_CIDR#*/}"
export IP_ADDRESS="${IP_ADDRESS_CIDR%%/"$CIDR"}"

exec node ./bin/docker-network-hosts -wco addn-hosts "$IP_ADDRESS"